### ISSUE TITLE
Admin Website Authentication

### ISSUE THREAD

**Issue by brian-rud** [brian-rud/osu-cs467-citizen-science#2]
I'm creating this issue so we have a place to talk about how we want to handle authentication on the admin website.

I found [this tutorial](https://auth0.com/blog/complete-guide-to-vue-user-authentication/#Get-the-Starter-Application) that I plan on following.  auth0 seems to be pretty widely used.

I'll update this issue as we begin implementing authentication in the Vue.js code but I thought this was a good starting point.

If anyone has strong opinions either for or against this approach then feel free to comment.

**Comment by beteivap** [comment]
Closing this since authentication has been implemented using Auth0.
